// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('open_menu', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('open_menu', async function() {
    await driver.findElement(By.id("header-right")).click()
    await driver.findElement(By.css(".active > .slideinframe-back-button")).click()
  })
})
